const BACKKUP = [
  {
    thumbnail: "https://i.ytimg.com/vi/6HwXFt1RPDU/hqdefault.jpg",
    title: "Sensational Door Illus...",
    channelTitle: "VamossART",
    publishedAt: "6/20/2017, 7:00:01 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/jeU46gusSQA/hqdefault.jpg",
    title: "50+ AMAZING ART IDEAS ...",
    channelTitle: "5-Minute Crafts",
    publishedAt: "11/23/2022, 7:00:26 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/TiDzmfQ_Y_4/hqdefault.jpg",
    title: "Drawing a surprise for...",
    channelTitle: "Kauczuk",
    publishedAt: "6/21/2024, 9:56:51 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/VYh8RT9kv24/hqdefault.jpg",
    title: "Spiral String Art - St...",
    channelTitle: "WooGlobe",
    publishedAt: "10/5/2021, 5:28:18 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/GgaNZBvUNWQ/hqdefault.jpg",
    title: "TOP 30 Easy Art Tips &...",
    channelTitle: "Quantastic",
    publishedAt: "12/8/2023, 8:00:11 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/GeHr-Xd3z1g/hqdefault.jpg",
    title: "Art Hacks For LAZY Art...",
    channelTitle: "Rae Dizzle Shorts",
    publishedAt: "9/14/2022, 4:01:28 AM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/0hS9ak34QSw/hqdefault.jpg",
    title: "MESMERIZING ART IDEAS ...",
    channelTitle: "5-Minute Crafts",
    publishedAt: "3/1/2022, 10:00:00 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/10I1ni6cE0k/hqdefault.jpg",
    title: "how to make a girl ❤️ ...",
    channelTitle: "anshu artss",
    publishedAt: "7/13/2024, 9:03:35 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/lIZSfetbZmo/hqdefault.jpg",
    title: "Send this to an artist...",
    channelTitle: "Yasmin Art Drawing",
    publishedAt: "10/20/2022, 4:43:02 AM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/4EcHEQdnWeY/hqdefault.jpg",
    title: "13 Types of Students i...",
    channelTitle: "JianHao Tan",
    publishedAt: "3/6/2022, 9:00:05 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/EHDOPl_hGd8/hqdefault.jpg",
    title: "COOL ART HACKS AND DIY...",
    channelTitle: "123 GO!",
    publishedAt: "8/23/2022, 10:00:13 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/8WBUsjaLJuo/hqdefault.jpg",
    title: "Blippi Creates Spin Ar...",
    channelTitle: "Blippi Wonders - Educational Cartoons for Kids",
    publishedAt: "10/17/2020, 6:00:03 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/KmxBfUOA6Js/hqdefault.jpg",
    title: "Drawing, But Red Side ...",
    channelTitle: "NashVibes Art",
    publishedAt: "5/24/2024, 5:25:15 AM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/YYT2yT61b4U/hqdefault.jpg",
    title: "This Artist has an Inc...",
    channelTitle: "Anthony Wreyn",
    publishedAt: "7/29/2023, 8:45:01 AM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/qDCY3EE23lQ/hqdefault.jpg",
    title: "easy aesthetic doodle ...",
    channelTitle: "Lia Hansen",
    publishedAt: "11/13/2022, 3:22:48 AM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/avxcc3hyCkU/hqdefault.jpg",
    title: "Which one did you thin...",
    channelTitle: "Yasmin Art Drawing",
    publishedAt: "8/18/2023, 3:57:50 AM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/t4TI4Gxyb4A/hqdefault.jpg",
    title: "DIGITAL🤖 VS TRADITION...",
    channelTitle: "JustinArts",
    publishedAt: "12/16/2023, 5:28:06 AM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/kqi_5HO5ouU/hqdefault.jpg",
    title: "How to draw a hand 🖐 ...",
    channelTitle: "Kelly Edelman",
    publishedAt: "7/2/2024, 9:55:04 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/rZ2jVwdUZqk/hqdefault.jpg",
    title: "These CAKE Artists Are...",
    channelTitle: "Quantastic",
    publishedAt: "3/31/2023, 1:00:34 AM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/vPYOEGcD9wY/hqdefault.jpg",
    title: "Trying fevicrly 3d Neo...",
    channelTitle: "Zany Art and Craft",
    publishedAt: "12/12/2022, 5:22:45 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/zvuv9rdGn0w/hqdefault.jpg",
    title: "ArtSS 1989",
    channelTitle: "UW4 / Dan W",
    publishedAt: "10/27/2023, 2:09:04 AM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/V14lDQFLlGg/hqdefault.jpg",
    title: "I ❤️U MOM #art #artwor...",
    channelTitle: "abit_bozdal",
    publishedAt: "6/22/2023, 12:42:19 AM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/O4i-KNUfeFs/hqdefault.jpg",
    title: "My art in Class vs At ...",
    channelTitle: "Artcoaster",
    publishedAt: "3/8/2022, 11:58:52 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/osyRXlEg4co/hqdefault.jpg",
    title: "ARTSS stainless steel ...",
    channelTitle: "Derangedsign",
    publishedAt: "4/16/2019, 3:57:42 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/A628Kt8FsNw/hqdefault.jpg",
    title: "How to Draw Pencil Ske...",
    channelTitle: "Modern Art Gallery",
    publishedAt: "7/27/2020, 12:16:16 AM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/7dxrPX72YkY/hqdefault.jpg",
    title: "Arabic Calligraphy for...",
    channelTitle: "Hussain Artss",
    publishedAt: "6/4/2023, 7:00:05 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/QZQyV9BB50E/hqdefault.jpg",
    title: "What is Art?",
    channelTitle: "LearnFree",
    publishedAt: "6/13/2018, 12:36:09 AM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/-bKufWHTDkE/hqdefault.jpg",
    title: "THINGS WE ALL DID AS B...",
    channelTitle: "Sarah Inoue",
    publishedAt: "9/14/2022, 7:57:49 AM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/kFdnj__2sbE/hqdefault.jpg",
    title: "My All Artworks , 2022 🔥",
    channelTitle: "Sanju Arts",
    publishedAt: "1/4/2023, 9:10:29 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/NL70_oWvnwo/hqdefault.jpg",
    title: "Artss😊😊",
    channelTitle: "mahak_arts_creation",
    publishedAt: "9/5/2020, 9:12:04 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/nAyleGd486I/hqdefault.jpg",
    title: "Draw Oranges! #art #dr...",
    channelTitle: "Howard Lee",
    publishedAt: "2/8/2024, 2:33:21 AM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/dFlNC4WvdeQ/hqdefault.jpg",
    title: "#artss#shorts",
    channelTitle: "mazza aayo",
    publishedAt: "3/7/2022, 7:10:49 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/N9oJONYzENs/hqdefault.jpg",
    title: "#starseverywhere #crea...",
    channelTitle: "Habon Artss and Crafts",
    publishedAt: "7/15/2024, 7:04:36 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/oTc65eJldeM/hqdefault.jpg",
    title: "my boyfriend reacted t...",
    channelTitle: "JULIA GISELLA",
    publishedAt: "2/25/2022, 10:00:19 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/PJWCyZNLnkk/hqdefault.jpg",
    title: "RANDOM Spinner TRANSFO...",
    channelTitle: "Hassan Draws",
    publishedAt: "5/19/2024, 11:05:44 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/YIOb5_WCsOY/hqdefault.jpg",
    title: "What Is Art?",
    channelTitle: "Aperture",
    publishedAt: "8/16/2022, 12:30:05 AM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/QdSZMFL7t_o/hqdefault.jpg",
    title: "artss",
    channelTitle: "It's Toca Parisᥫ᭡!",
    publishedAt: "4/6/2024, 7:32:19 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/cToEUlJvAsc/hqdefault.jpg",
    title: "Tiana has a weird habi...",
    channelTitle: "CreativeCat Moms",
    publishedAt: "3/11/2024, 10:00:50 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/IHgxQDNbvjk/hqdefault.jpg",
    title: "#starseverywhere #crea...",
    channelTitle: "Habon Artss and Crafts",
    publishedAt: "7/14/2024, 6:27:13 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/iET0fjgtbTU/hqdefault.jpg",
    title: "#artss#shorts",
    channelTitle: "mazza aayo",
    publishedAt: "3/7/2022, 7:11:07 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/crVU25v_aps/hqdefault.jpg",
    title: "How to make Towel Anim...",
    channelTitle: "CITRA SHAYMA",
    publishedAt: "4/17/2023, 7:00:23 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/ks5PA_CA-wI/hqdefault.jpg",
    title: "#artss#shorts",
    channelTitle: "mazza aayo",
    publishedAt: "3/5/2022, 7:11:41 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/dleVn6FD8LQ/hqdefault.jpg",
    title: "3 LIFE-CHANGING art ha...",
    channelTitle: "isabella.drawsss",
    publishedAt: "12/6/2022, 4:42:42 AM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/DKdcPe5flIc/hqdefault.jpg",
    title: "Lover//Taylor Swift (s...",
    channelTitle: "Chuckie Artsss",
    publishedAt: "2/23/2022, 11:37:29 AM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/Fx36A2cJxhY/hqdefault.jpg",
    title: "#artss#shorts",
    channelTitle: "mazza aayo",
    publishedAt: "3/5/2022, 7:12:20 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/IyLzLQw9SLM/hqdefault.jpg",
    title: "#artss#shorts",
    channelTitle: "mazza aayo",
    publishedAt: "3/7/2022, 7:12:35 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/3m8aOQuEPD0/hqdefault.jpg",
    title: "Artss",
    channelTitle: "goutham K Nishad",
    publishedAt: "5/22/2024, 4:33:03 PM",
  },
  {
    thumbnail: "https://i.ytimg.com/vi/v-8OKOSqavY/hqdefault.jpg",
    title: "How To Draw Princess C...",
    channelTitle: "Art for Kids Hub",
    publishedAt: "10/15/2015, 5:11:32 AM",
  },
];
